from langchain_openai import ChatOpenAI
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough, RunnableMap, RunnableLambda
import pickle
import re
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
import os


os.environ["GOOGLE_API_KEY"]
llm = ChatGoogleGenerativeAI(model="gemini-3-flash-preview")


template_log_parser = ChatPromptTemplate.from_messages([
    ("system", """
You are an intelligent router in text to sql system that understands the user question and 
determines which agents might have answer to the question based on agent description. Multiple agents might answer a given user question. OUTPUT SHOULD BE IN FORM OF LIST OF strings.
Dont give any explanation or any other verbose in the output.
"""),

    ("human", '''
User question:
{question}

     ''')
])

# Fix the RunnableMap implementation
chain_log_parser = (
    RunnableMap({
        "question": lambda x: x["question"]
    })
    | template_log_parser
    | llm 
    | StrOutputParser()
)



template_error_detector = ChatPromptTemplate.from_messages([
    ("system", """
     You are an Error Detection Agent specialized in analyzing parsed log data to identify and summarize errors.
The output generated by you will be used in further steps of a multi-agent workflow for root cause analysis and solution generation.
So please keep in mind while generating the output.
Your task is to identify, group, and summarize errors strictly from the provided parsed log data.

You must follow these rules:
- Use ONLY the information explicitly present in the input data.
- Do NOT infer root causes.
- Do NOT suggest solutions.
- Do NOT invent error codes, components, or messages.
- If a field is not present in the data, set it to null.
- Every identified error MUST be supported by evidence from the logs.
- If no errors are found, return an empty result with an explanation.

Your output must be valid JSON and must strictly follow the provided schema.

"""),

    ("human", '''
Below is the parsed log data which you need to analyze for error detection.
Parsed log contains multiple log entries with various levels such as ERROR, WARN, and INFO.
It contains details about file name, timestamps, error messages.
Your main task is to read the parsed log data carefully.
parsed entries contains details about the error like error message, error code, component, timestamps, raw line which is exact line from log file
Analyze the data and produce an error detection report following the exact JSON schema.

Parsed Logs:
{parsed_logs_json}

Return ONLY valid JSON in the following format:
{{
  "error_summary": {{
    "total_errors": int,
    "unique_error_types": int,
    "time_range": {{
      "start": "ISO-8601 timestamp or null",
      "end": "ISO-8601 timestamp or null"
    }}
  }},
  "identified_errors": [
    {{
      "error_id": "ERR-XXX",
      "message": "string",
      "error_code": "string or null",
      "level": "ERROR or WARN",
      "component": "string or null",
      "frequency": int,
      "first_seen": "ISO-8601 timestamp or null",
      "last_seen": "ISO-8601 timestamp or null",
      "affected_files": ["string"],
      "stack_trace_present": boolean,
      "evidence": {{
        "sample_lines": ["string"]
      }}
    }}
  ]
}}
     ''')
])

# Fix the RunnableMap implementation
chain_error_detector = (
    RunnableMap({
        "parsed_log_json": lambda x: x["parsed_log_json"]
    })
    | template_error_detector
    | llm 
    | StrOutputParser()
)

template_root_cause_analyzer = ChatPromptTemplate.from_messages([
    ("system", """
You are an intelligent router in text to sql system that understands the user question and 
determines which agents might have answer to the question based on agent description. Multiple agents might answer a given user question. OUTPUT SHOULD BE IN FORM OF LIST OF strings.
Dont give any explanation or any other verbose in the output.
"""),

    ("human", '''
User question:
{question}

     ''')
])

# Fix the RunnableMap implementation
chain_root_cause_analyzer = (
    RunnableMap({
        "question": lambda x: x["question"]
    })
    | template_root_cause_analyzer
    | llm 
    | StrOutputParser()
)

template_generate_solution = ChatPromptTemplate.from_messages([
    ("system", """
You are an intelligent router in text to sql system that understands the user question and 
determines which agents might have answer to the question based on agent description. Multiple agents might answer a given user question. OUTPUT SHOULD BE IN FORM OF LIST OF strings.
Dont give any explanation or any other verbose in the output.
"""),

    ("human", '''
User question:
{question}

     ''')
])

# Fix the RunnableMap implementation
chain_generate_solution = (
    RunnableMap({
        "question": lambda x: x["question"]
    })
    | template_generate_solution
    | llm 
    | StrOutputParser()
)


template_report_generator = ChatPromptTemplate.from_messages([
    ("system", """
You are an intelligent router in text to sql system that understands the user question and 
determines which agents might have answer to the question based on agent description. Multiple agents might answer a given user question. OUTPUT SHOULD BE IN FORM OF LIST OF strings.
Dont give any explanation or any other verbose in the output.
"""),

    ("human", '''
User question:
{question}

     ''')
])

# Fix the RunnableMap implementation
chain_report_generator = (
    RunnableMap({
        "question": lambda x: x["question"]
    })
    | template_report_generator
    | llm 
    | StrOutputParser()
)
